export const BIKER_CREATE_MODAL = "BIKER_CREATE_MODAL";
export const BIKER_EDIT_MODAL = "BIKER_EDIT_MODAL";
export const BIKER_DELETE_MODAL = "BIKER_DELETE_MODAL";
export const BIKER_DETAIL_MODAL = "BIKER_DETAIL_MODAL";
