export const CUSTOMER_CREATE_MODAL = "CUSTOMER_CREATE_MODAL ";
export const CUSTOMER_EDIT_MODAL = "CUSTOMER_EDIT_MODAL";
export const CUSTOMER_DELETE_MODAL = "CUSTOMER_DELETE_MODAL";
export const CUSTOMER_DETAIL_MODAL = "CUSTOMER_DETAIL_MODAL";
