export const GET_CUSTOMER = "GET_CUSTOMER";
export const SET_CUSTOMER = "SET_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const UPDATE_CUSTOMER_PASSWORD = "UPDATE_CUSTOMER_PASSWORD";
